name: render-slides-with-marp

on:
  push:
    branches: [ master ]
    paths: 
      - "_slides/**"

jobs:
  render-slides:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build slides
        uses: docker://marpteam/marp-cli:v2.0.4
        with:
          args: -I _slides/ --output slides/
        env:
          MARP_USER: root:root
      - name: Copy and Alter Front Matter
        run: |
           mkdir -p _talks  # Ensure the _talks directory exists
             for file in _slides/*.md; do
                 filename=$(basename -- "$file")
                 basename="${filename%.*}"
                 { 
                 awk '/^---$/{print; if(flag) exit; flag=1; next} flag' "$file";
                 echo "[See slides/poster](https://simhydro.com/slides/$basename.html)";
                 } > "_talks/$filename"
             done
      - name: Push to Branch
        run: |
          git config user.name 'marp slides build'
          git config user.email 'hydrotian@users.noreply.github.com'
          git checkout -b "slides-${{github.run_id}}"
          git add slides/*
          git add _talks/*
          git add _slides/*
          git commit -m "feat: Add rendered slides"
          git push --set-upstream origin "slides-${{github.run_id}}"
      - name: Open PR
        run: | 
          curl   -X POST \
          -f \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          https://api.github.com/repos/hydrotian/hydrotian.github.io/pulls \
          -d '{"title":"Add rendered slides","body":"Adding rendered slides","head":"slides-${{github.run_id}}","base":"master"}'